"""Frozen evaluation sets of Puck2D task instances (Gate 1, REQ-SIM, REQ-REPRO; ENG-0008).

A :class:`TaskInstance` is one reach task: start, goal, obstacles and a
disturbance schedule (:class:`~simulation.puck2d.Impulse` /
:class:`~simulation.puck2d.MassChange`) plus the episode seed. An
:class:`EvaluationSet` is an immutable, ordered tuple of tasks generated by
:func:`build_evaluation_set` from one seed; it is saved as JSON and loaded back
unchanged (``EvaluationSet.from_json(s.to_json()) == s``). Evaluation sets are
fixed before results are produced; :meth:`EvaluationSet.fingerprint` (SHA-256 of
the canonical JSON) identifies one in experiment records.

Generation (all draws from ``numpy.random.default_rng(seed)``, in task order):
start and goal uniform in the arena box with ``|goal - start| >=
min_start_goal_dist``; obstacles (count uniform in ``n_obstacles``) are discs
with radius uniform in ``obstacle_radius``, rejection-sampled so they keep
``clearance`` from the start and the goal disc; impulses / mass changes at
steps uniform in ``disturbance_steps``, impulse components uniform in
``[-impulse_max, impulse_max]``, masses uniform in ``mass_range``.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Union

import numpy as np

from simulation.puck2d import Impulse, MassChange, Obstacle, Puck2DConfig

EVALSET_VERSION = "evalset-0.1.0"
_MAX_SAMPLES = 10_000


def _pair(value: Any, name: str) -> tuple[float, float]:
    out = tuple(float(v) for v in value)
    if len(out) != 2 or not all(math.isfinite(v) for v in out):
        raise ValueError(f"{name} must be two finite numbers, got {value!r}")
    return out  # type: ignore[return-value]


def _strict_keys(raw: Any, cls: type, name: str) -> None:
    if not isinstance(raw, Mapping):
        raise ValueError(f"{name}: expected object, got {type(raw).__name__}")
    names = {f.name for f in dataclasses.fields(cls)}
    missing, unknown = sorted(names - set(raw)), sorted(set(raw) - names)
    if missing or unknown:
        raise ValueError(f"{name}: missing {missing}, unknown {unknown}")


@dataclass(frozen=True)
class TaskInstance:
    """One reach task; ``seed`` seeds the environment and the runner of its episode."""

    task_id: str
    seed: int
    start: tuple[float, float]
    goal: tuple[float, float]
    obstacles: tuple[Obstacle, ...] = ()
    impulses: tuple[Impulse, ...] = ()
    mass_changes: tuple[MassChange, ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.task_id, str) or not self.task_id:
            raise ValueError("task_id must be a non-empty str")
        if isinstance(self.seed, bool) or not isinstance(self.seed, int) or self.seed < 0:
            raise ValueError(f"seed must be a non-negative int, got {self.seed!r}")
        object.__setattr__(self, "start", _pair(self.start, "start"))
        object.__setattr__(self, "goal", _pair(self.goal, "goal"))
        for name, cls in (("obstacles", Obstacle), ("impulses", Impulse),
                          ("mass_changes", MassChange)):
            items = tuple(x if isinstance(x, cls) else cls(**x) for x in getattr(self, name))
            object.__setattr__(self, name, items)

    def env_config(self, base: Puck2DConfig) -> Puck2DConfig:
        """``base`` with this task's start, goal, obstacles and disturbances."""
        return dataclasses.replace(
            base,
            start_pos=self.start,
            goal=self.goal,
            obstacles=self.obstacles,
            impulses=self.impulses,
            mass_changes=self.mass_changes,
        )

    def to_dict(self) -> dict[str, Any]:
        return json.loads(json.dumps(dataclasses.asdict(self), allow_nan=False))

    @classmethod
    def from_dict(cls, raw: Any) -> "TaskInstance":
        _strict_keys(raw, cls, "TaskInstance")
        return cls(**raw)


@dataclass(frozen=True)
class EvaluationSet:
    """Ordered, immutable list of tasks plus the parameters that generated it."""

    name: str
    seed: int
    params: Mapping[str, Any]
    tasks: tuple[TaskInstance, ...]
    version: str = EVALSET_VERSION

    def __post_init__(self) -> None:
        if not isinstance(self.name, str) or not self.name:
            raise ValueError("name must be a non-empty str")
        # JSON-native params (tuples -> lists) so a JSON round trip is the identity.
        object.__setattr__(self, "params", json.loads(json.dumps(dict(self.params), allow_nan=False)))
        tasks = tuple(t if isinstance(t, TaskInstance) else TaskInstance.from_dict(t)
                      for t in self.tasks)
        ids = [t.task_id for t in tasks]
        if len(set(ids)) != len(ids):
            raise ValueError("task_id values must be unique")
        object.__setattr__(self, "tasks", tasks)

    def __len__(self) -> int:
        return len(self.tasks)

    def __iter__(self):
        return iter(self.tasks)

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "seed": self.seed,
            "params": dict(self.params),
            "tasks": [t.to_dict() for t in self.tasks],
            "version": self.version,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), allow_nan=False, sort_keys=True, indent=1)

    @classmethod
    def from_dict(cls, raw: Any) -> "EvaluationSet":
        _strict_keys(raw, cls, "EvaluationSet")
        if raw["version"] != EVALSET_VERSION:
            raise ValueError(f"evaluation set version {raw['version']!r} != {EVALSET_VERSION!r}")
        return cls(**raw)

    @classmethod
    def from_json(cls, text: str) -> "EvaluationSet":
        return cls.from_dict(json.loads(text))

    def fingerprint(self) -> str:
        return hashlib.sha256(self.to_json().encode("utf-8")).hexdigest()

    def save(self, path: Union[str, os.PathLike]) -> Path:
        """Write the set as JSON; refuses to overwrite (a frozen set is never rewritten)."""
        p = Path(path)
        with open(p, "x", encoding="utf-8") as fh:
            fh.write(self.to_json())
        return p

    @classmethod
    def load(cls, path: Union[str, os.PathLike]) -> "EvaluationSet":
        return cls.from_json(Path(path).read_text(encoding="utf-8"))


def build_evaluation_set(
    seed: int,
    n_tasks: int,
    *,
    name: str = "puck2d-eval",
    arena_low: tuple[float, float] = (-1.0, -1.0),
    arena_high: tuple[float, float] = (1.0, 1.0),
    min_start_goal_dist: float = 0.5,
    goal_radius: float = 0.05,
    n_obstacles: tuple[int, int] = (0, 0),
    obstacle_radius: tuple[float, float] = (0.05, 0.15),
    clearance: float = 0.1,
    n_impulses: tuple[int, int] = (0, 0),
    impulse_max: float = 0.5,
    n_mass_changes: tuple[int, int] = (0, 0),
    mass_range: tuple[float, float] = (0.5, 2.0),
    disturbance_steps: tuple[int, int] = (0, 200),
) -> EvaluationSet:
    """Generate ``n_tasks`` tasks deterministically from ``seed`` (see module doc).

    Count ranges ``(lo, hi)`` are inclusive.
    """
    if isinstance(seed, bool) or not isinstance(seed, int) or seed < 0:
        raise ValueError(f"seed must be a non-negative int, got {seed!r}")
    if isinstance(n_tasks, bool) or not isinstance(n_tasks, int) or n_tasks < 0:
        raise ValueError(f"n_tasks must be a non-negative int, got {n_tasks!r}")
    params = dict(
        n_tasks=n_tasks, arena_low=arena_low, arena_high=arena_high,
        min_start_goal_dist=min_start_goal_dist, goal_radius=goal_radius,
        n_obstacles=n_obstacles, obstacle_radius=obstacle_radius, clearance=clearance,
        n_impulses=n_impulses, impulse_max=impulse_max, n_mass_changes=n_mass_changes,
        mass_range=mass_range, disturbance_steps=disturbance_steps,
    )
    lo, hi = np.array(_pair(arena_low, "arena_low")), np.array(_pair(arena_high, "arena_high"))
    if not np.all(lo < hi):
        raise ValueError("arena_low must be < arena_high")
    rng = np.random.default_rng(seed)

    def count(rng_: np.random.Generator, r: tuple[int, int]) -> int:
        return int(rng_.integers(r[0], r[1] + 1))

    def point() -> np.ndarray:
        return rng.uniform(lo, hi)

    tasks = []
    for i in range(n_tasks):
        task_seed = int(rng.integers(0, 2**31 - 1))
        for _ in range(_MAX_SAMPLES):
            start, goal = point(), point()
            if np.hypot(*(goal - start)) >= min_start_goal_dist:
                break
        else:
            raise ValueError("could not sample start/goal; arena too small for min_start_goal_dist")

        obstacles = []
        for _ in range(count(rng, n_obstacles)):
            for _ in range(_MAX_SAMPLES):
                c = point()
                r = float(rng.uniform(*obstacle_radius))
                if (np.hypot(*(c - start)) > r + clearance
                        and np.hypot(*(c - goal)) > r + goal_radius + clearance):
                    break
            else:
                raise ValueError("could not place an obstacle clear of start and goal")
            obstacles.append(Obstacle((float(c[0]), float(c[1])), r))

        impulses = []
        for _ in range(count(rng, n_impulses)):
            k = int(rng.integers(disturbance_steps[0], disturbance_steps[1] + 1))
            j = rng.uniform(-impulse_max, impulse_max, 2)
            impulses.append(Impulse(k, (float(j[0]), float(j[1]))))

        mass_changes: dict[int, MassChange] = {}
        for _ in range(count(rng, n_mass_changes)):
            k = int(rng.integers(disturbance_steps[0], disturbance_steps[1] + 1))
            m = float(rng.uniform(*mass_range))
            mass_changes.setdefault(k, MassChange(k, m))  # Puck2D: one change per step

        tasks.append(TaskInstance(
            task_id=f"{name}-{i:04d}",
            seed=task_seed,
            start=(float(start[0]), float(start[1])),
            goal=(float(goal[0]), float(goal[1])),
            obstacles=tuple(obstacles),
            impulses=tuple(sorted(impulses, key=lambda x: x.step)),
            mass_changes=tuple(mass_changes[k] for k in sorted(mass_changes)),
        ))
    return EvaluationSet(name=name, seed=seed, params=params, tasks=tuple(tasks))
